In [ ]:
import urllib

In [ ]:
def get_dmy(date):
  date = date.split(".")
  return date[0], date[1], date[2]

def get_period_num(s):
  time_period = {
    "tick": 1,
    "min": 2,
    "5 min": 3,
    "10 min": 4,
    "15 min": 5,
    "30 min": 6,
    "hour": 7,
    "day": 8,
    "week": 9,
    "month": 10
  }
  return time_period[s]

In [ ]:
def quotes(code,
           yf, month_start, day_start,
           yt, month_end, day_end,
           market,
           em,
           p):

# ----------------------------------------------------------------------------------------------------------------------------------
  # HARDCODE VARIBLES

  e = '.csv' # формат файла txt/csv

  dtf = '4' # формат даты (1 — ггггммдд, 2 — ггммдд, 3 — ддммгг, 4 — дд/мм/гг, 5 — мм/дд/гг)
  tmf = '1' # формат времени (1 — ччммсс, 2 — ччмм, 3 — чч: мм: сс, 4 — чч: мм)
  MSOR = '1' # выдавать время (0 — начала свечи, 1 — окончания свечи)
  mstimever = '1' # выдавать время (НЕ московское — mstimever=0; московское — mstime='on', mstimever='1')

  sep = '1' # параметр разделитель полей (1 — запятая (,), 2 — точка (.), 3 — точка с запятой (;), 4 — табуляция (»), 5 — пробел ( ))
  sep2 = '1' # параметр разделитель разрядов (1 — нет, 2 — точка (.), 3 — запятая (,), 4 — пробел ( ), 5 — кавычка ('))

  datf = '1' # Перечень получаемых данных (
      #1 — TICKER, PER, DATE, TIME, OPEN, HIGH, LOW, CLOSE, VOL;
      #2 — TICKER, PER, DATE, TIME, OPEN, HIGH, LOW, CLOSE;
      #3 — TICKER, PER, DATE, TIME, CLOSE, VOL;
      #4 — TICKER, PER, DATE, TIME, CLOSE;
      #5 — DATE, TIME, OPEN, HIGH, LOW, CLOSE, VOL;
      #6 — DATE, TIME, LAST, VOL, ID, OPER).

  at = '1' # добавлять заголовок в файл (0 — нет, 1 — да)
# ----------------------------------------------------------------------------------------------------------------------------------
  mf = (int(month_start.replace('0', ''))) - 1
  mt = (int(month_end.replace('0', ''))) - 1

  df = (int(day_start.replace('0', ''))) - 1
  dt = (int(day_end.replace('0', ''))) - 1

  year_start = yf[2:]
  year_end = yt[2:]
# ----------------------------------------------------------------------------------------------------------------------------------

  page = urllib.request.urlopen(
        'http://export.finam.ru/' +
        str(code) + '_' +
        str(year_start) + str(month_start) + str(day_start) + '_' +
        str(year_end) + str(month_end) + str(day_end) +
        str(e) +

        '?market=' + str(market) +
        '&em=' + str(em) +
        '&code=' + str(code) +
        '&apply=0&df=' + str(df) +
        '&mf=' + str(mf) +
        '&yf=' + str(yf) +

        '&from=' + str(day_start) + '.' + str(month_start) + '.' + str(yf) +
        '&dt=' + str(dt) + '&mt=' + str(mt) + '&yt=' + str(yt) +
        '&to=' + str(day_end) + '.' + str(month_end) + '.' + str(yt) +

        '&p=' + str(p) +
        '&f=' + str(code) + '_' +
        str(year_start) + str(month_start) + str(day_start) + '_' +
        str(year_end) + str(month_end) + str(day_end) +

        '&e=' + str(e) +
        '&cn=' + str(code) +
        '&dtf=' + str(dtf) +
        '&tmf=' + str(tmf) +
        '&MSOR=' + str(MSOR) +
        '&mstimever=' + str(mstimever) +

        '&sep=' + str(sep) +
        '&sep2=' + str(sep2) +

        '&datf=' + str(datf) +
        '&at=' + str(at))

  f = open(f'{code}_from_{yf}_{month_start}_{day_start}_to_{yt}_{month_end}_{day_end}.csv', "wb")
  content = page.read()
  f.write(content)
  f.close()

  if len(content) > 100:
    print("OK")
  else:
    print("ERROR FOR " + f'{code}_from_{yf}_{month_start}_{day_start}_to_{yt}_{month_end}_{day_end}.csv')

In [ ]:
def get_stocks_info(ticker, market, period, date_start, date_end):
  date_start = get_dmy(date_start)
  day_start = date_start[0]
  month_start = date_start[1]
  yf = date_start[2]

  date_end = get_dmy(date_end)
  day_end = date_end[0]
  month_end = date_end[1]
  yt = date_end[2]

  p = get_period_num(period)

  quotes(code, yf, month_start, day_start, yt,month_end, day_end, market, em, p)

In [ ]:
code = 'YNDX' # тикер
em = '388383' # символьная переменная по инструменту (id тикета)
market = '1' # требует сбора - то где торгуется (инструмент) 1 - МосБиржа акции
period = 'min' # период котировок (тики, 1 мин., 5 мин., 10 мин., 15 мин., 30 мин., 1 час, 1 день, 1 неделя, 1 месяц)

date_start = "20.05.2017"
date_end = "20.06.2017"

In [ ]:
get_stocks_info(code, market, period, date_start, date_end)

http://export.finam.ru/YNDX_170520_170620.csv?market=1&em=175924&code=YNDX&apply=0&df=1&mf=4&yf=2017&from=20.05.2017&dt=1&mt=5&yt=2017&to=20.06.2017&p=2&f=YNDX_170520_170620&e=.csv&cn=YNDX&dtf=4&tmf=1&MSOR=1&mstimever=1&sep=1&sep2=1&datf=1&at=1
OK

In [ ]:
import pandas as pd

pd.read_csv('YNDX_from_2017_05_20_to_2017_06_20.csv')

     <TICKER>  <PER>    <DATE>  <TIME>  <OPEN>  <HIGH>  <LOW>  <CLOSE>  <VOL>
0        YNDX      1  02/05/17  100100   747.0   756.0  744.0    745.0   2300
1        YNDX      1  02/05/17  100200   745.0   746.5  744.0    745.5    412
2        YNDX      1  02/05/17  100300   746.0   746.5  744.5    745.5    257
3        YNDX      1  02/05/17  100400   744.0   744.0  741.0    742.0   1271
4        YNDX      1  02/05/17  100500   742.0   742.0  741.0    742.0    216
...       ...    ...       ...     ...     ...     ...    ...      ...    ...
5908     YNDX      1  01/06/17  183700   720.5   720.5  720.0    720.0     15
5909     YNDX      1  01/06/17  183800   720.0   720.0  718.0    719.0    423
5910     YNDX      1  01/06/17  183900   718.0   718.0  718.0    718.0    398
5911     YNDX      1  01/06/17  184000   718.0   719.0  718.0    718.0    438
5912     YNDX      1  01/06/17  184600   718.0   718.0  718.0    718.0     70

[5913 rows x 9 columns]